### ISSUE TITLE
Don't connect

### ISSUE THREAD

**Issue by lousyDire** [WantedSwift/sampleWiregard#1]
I can’t connect at all, unfortunately it doesn’t even write anything due to errors, maybe I’m entering the configuration in the wrong place

**Comment by WantedSwift** [comment]
You must first index Wireguard according to the documentation.
Then make the names of all the groups the same.
and make the version and build targets the same.
check the settings of the VPN device and make sure the configuration is correct.

**Comment by lousyDire** [comment]
The configuration is correct, maybe I’m just entering it in the wrong place, I did everything as written in the last post
