### ISSUE TITLE
unable to spawn process

### ISSUE THREAD

**Issue by Jenil1501** [WantedSwift/sampleWiregard#3]
error: unable to spawn process '/usr/bin/make' (No such file or directory) (in target 'WireGuardGoBridgeiOS')

**Comment by WantedSwift** [comment]
[wireguard-apple-master.zip](https://github.com/WantedSwift/sampleWiregard/files/13805692/wireguard-apple-master.zip)

Download this zip and extract on your desktop(only desktop) and set Directory address in WireGuardGoBridgeiOS like this screenshot
Done!
![Screenshot 2024-01-01 at 11 10 47 PM](https://github.com/WantedSwift/sampleWiregard/assets/73441118/177d265b-3b40-446d-93d0-a2649bcab0a3)
