### ISSUE TITLE
IPC failed

### ISSUE THREAD

**Issue by Jenil1501** [WantedSwift/sampleWiregard#4]
I am getting this error can you help me with solution :- 

ERROR NetworkExtensionVPN.notifyInstallError():252 - VPN installation failed: Error Domain=NEVPNErrorDomain Code=5 "IPC failed" UserInfo={NSLocalizedDescription=IPC failed})

**Comment by WantedSwift** [comment]
you use simulator?

**Comment by Jenil1501** [comment]
No,  I used physical device
But I read some where on internet that for connection I need entitlements
file I don't what it is can you help ?

**Comment by WantedSwift** [comment]
if fixed this problem pull again!
